[34m[1mwandb[0m: Downloading large artifact NewDataset:v0, 1419.75MB. 27558 files...
Exception ignored in: <function ZipFile.__del__ at 0x107fb5e40>
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/zipfile.py", line 1895, in __del__
    self.close()0m: / 5001 of 27558 files downloaded...
  File "/opt/homebrew/Caskroom/miniforge/base/envs/ComputerVision/lib/python3.11/zipfile.py", line 1912, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file
[34m[1mwandb[0m:   27558 of 27558 files downloaded.  
Done. 0:1:3.9
